name: Release and Deploy to Render

on:
  push:
    tags:
      - 'v*'

jobs:
  release-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python Dependencies
        run: pip install pyyaml

      - name: Update Concert Galleries
        run: python script/auto_update_all_galleries.py

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: script/Dockerfile
          push: true
          tags: |
            codexgrid/jekyll:${{ github.ref_name }}
            codexgrid/jekyll:latest

      - name: Trigger Render Deploy Hook (imgURL)
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}&imgURL=docker.io/codexgrid/jekyll:${{ github.ref_name }}"