name: Release and Deploy to Render

on:
  push:
    tags:
      - 'v*'  # version trigger for render pull seclection

jobs:
  release-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: script/Dockerfile
          push: true
          tags: |
            codexgrid/jekyll:${{ github.ref_name }}
            codexgrid/jekyll:latest

#      - name: Trigger Render Deploy Hook (imgURL)
#        run: |
#          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}&imgURL=docker.io/yourdockerhub/your-repo:${{ github.ref_name }}"
